### ISSUE TITLE
Read -token, -accountid, -appname from environment variables

### ISSUE THREAD

**Issue by upward4** [dvcrn/maskedemail-cli#6]
It would be nice to support reading global parameters like these as environment variables, so that they do not need to be passed as CLI flags. For example, -token could be $MASKEDEMAIL_TOKEN.

**Comment by earthboundkid** [comment]
I came to suggest the same thing. If you're willing to add a dependency, the simplest way to do this is to import github.com/carlmjohnson/flagx and add a line after `flag.Parse()` [`flagx.ParseEnv(nil, "MASKED_EMAIL")`](https://pkg.go.dev/github.com/carlmjohnson/flagx#ParseEnv).

**Comment by dvcrn** [comment]
@1pav just implemented this in #7 👍
